spring:
  application:
    name: eureka-server
server:
 port: 8761

eureka:
  client:
    register-with-eureka: false   # Server does not register itself
    fetch-registry: false         # Server does not fetch registry
  server:
    enable-self-preservation: false
#logs 
logging:
 pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
 file:
    name: C:\Users\sowja\OneDrive\Documents\online_expenses_tracker_logs\eureka_logs\eureka_logs.log
 level:
    ROOT: INFO                       # Default global log level
    org.springframework: WARN         # Spring internal logs at WARN
    com.sowja.demoh2: DEBUG 
 logback:
    rollingpolicy:
      max-file-size: 1MB       # maximum size per log file
      max-history: 5      

