spring:
  application:
    name: apigateway-server
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
        - id: expenses-server
          uri: lb://EXPENSES-SERVER
          predicates:
            - Path=/expenses/**,/reportsummery/**
        - id: category-server
          uri: lb://CATEGORY-SERVER
          predicates:
            - Path=/category/**

server:
  port: 8080
#logs 
logging:
 pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
 file:
    name: C:\Users\sowja\OneDrive\Documents\online_expenses_tracker_logs\apiGateWay_logs\apigateway.log
 level:
    ROOT: INFO                       # Default global log level
    org.springframework: WARN         # Spring internal logs at WARN
    com.sowja.demoh2: DEBUG 
 logback:
    rollingpolicy:
      max-file-size: 1MB       # maximum size per log file
      max-history: 5       
  
